---
# tasks file for prod
- name: install tomcat
  apt:
   name: tomcat8
   state: present

- name: copy war from deploy server to prod
  copy: 
   src: "{{ artifact }}"
   dest: "{{ tomcat_dir }}"
  notify:
  - restart tomcat  
