---
# tasks file for deploy
- name: install packages
  apt: name={{item}} state=present
  with_items:
    - default-jre
    - git
    - maven

- name: git clone boxfuse
  git:
   repo: "{{ repo_url }}"
   dest: "{{ workspace }}"

- name: build application
  shell: mvn package chdir="{{ workspace }}"
  run_once: true

- name: copy artifact from deploy to master host
  fetch:
    src: "{{ artifact }}"
    dest: "{{ local_tmp }}"
